require File.expand_path('../boot', __FILE__)

require 'rails/all'

# this is required to prevent errors.
require 'csv'
require 'rubygems/package'
require 'trie'

if defined?(Bundler)
  # If you precompile assets before deploying to production, use this line
  Bundler.require(*Rails.groups(:assets => %w(development test)))
  # If you want your assets lazily compiled in production, use this line
  # Bundler.require(:default, :assets, Rails.env)
end

# Basic Application Module as generated by Rails.
module SnupyAgain
  class Application < Rails::Application
    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration should go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded.

    # Custom directories with classes and modules you want to be autoloadable.
    # config.autoload_paths += %W(#{config.root}/extras)
    
    ## SGinze2s: This results in too many folders inside the auto load path
		# config.autoload_paths += Dir["#{config.root}/extras/**/"]
		# Sginze2s: Prevent annotation directories to pollute the load path
		# Sginze2s: Load extras root directory first
		
		config.autoload_paths += (Dir["#{config.root}/lib/*"])
		config.autoload_paths += (Dir["#{config.root}/extras/**/"] - Dir["#{config.root}/extras/snupy_again/**/"])
		
		# COMMENT by Sginze2s: The Auqa Framework will not be added to the autoload path as it messes with refreshing the classes during development
		#                      Use Aqua._reload() in case you need to reload the class sources during development.
		# Sginze2s: Load Aqua framework
		# config.autoload_paths += Dir["#{config.root}/lib/aqua/"]
		# config.autoload_paths += Dir["#{config.root}/lib/aqua/annotation/"]
		# config.autoload_paths += Dir["#{config.root}/lib/aqua/query/"]
		# config.autoload_paths += Dir["#{config.root}/lib/aqua/aggregation/"]
		# config.autoload_paths += Dir["#{config.root}/extras/snupy_again/aqua/**/**/**"] # removed by sginze2s because this results in 23.000 files when VEP is setup
		# Singze2s: Load aqua modules
		# config.autoload_paths += Dir["#{config.root}/extras/snupy_again/aqua/annotations/*"]
		# config.autoload_paths += Dir["#{config.root}/extras/snupy_again/aqua/queries/*"]
		# config.autoload_paths += Dir["#{config.root}/extras/snupy_again/aqua/filters/*"]
		# config.autoload_paths += Dir["#{config.root}/extras/snupy_again/aqua/aggregations/*"]
		# Sginze2s: Load other stuff
		# config.autoload_paths += Dir["#{config.root}/lib/vep/"]
		# config.autoload_paths += Dir["#{config.root}/extras/snupy_again/"]
		
		#config.autoload_paths += Dir["#{config.root}/extras/snupy_again/query_attribute_group/"]
		config.autoload_paths += Dir["#{config.root}/extras/snupy_again/statistic_collector/**/"]
		#config.autoload_paths += Dir["#{config.root}/app/models/query_filter/**/"]
		#config.autoload_paths += Dir["#{config.root}/app/models/query_attribute/**/"]
		config.autoload_paths += Dir["#{config.root}/app/models/generic_list/**/"]
		config.autoload_paths += Dir["#{config.root}/app/models/vcf_file/**/"]
		config.autoload_paths += Dir["#{config.root}/app/models/statistic/**/"]
		
#		config.eager_load_paths += Dir["#{config.root}/app/models/query_filter/**/"]
#		config.eager_load_paths += Dir["#{config.root}/app/models/query_attribute/**/"]
#		config.eager_load = true

    # Only load the plugins named here, in the order given (default is alphabetical).
    # :all can be used as a placeholder for all plugins not explicitly named.
    # config.plugins = [ :exception_notification, :ssl_requirement, :all ]

    # Activate observers that should always be running.
    # config.active_record.observers = :cacher, :garbage_collector, :forum_observer

    # Set Time.zone default to the specified zone and make Active Record auto-convert to this zone.
    # Run "rake -D time" for a list of tasks for finding time zone names. Default is UTC.
    # config.time_zone = 'Central Time (US & Canada)'

    # The default locale is :en and all translations from config/locales/*.rb,yml are auto loaded.
    # config.i18n.load_path += Dir[Rails.root.join('my', 'locales', '*.{rb,yml}').to_s]
    # config.i18n.default_locale = :de

    # Configure the default encoding used in templates for Ruby 1.9.
    config.encoding = "utf-8"

    # Configure sensitive parameters which will be filtered from the log file.
    config.filter_parameters += [:password]

    # Enable escaping HTML in JSON.
    config.active_support.escape_html_entities_in_json = true

    # Use SQL instead of Active Record's schema dumper when creating the database.
    # This is necessary if your schema can't be completely dumped by the schema dumper,
    # like if you have constraints or database-specific column types
    # config.active_record.schema_format = :sql

    # Enforce whitelist mode for mass assignment.
    # This will create an empty whitelist of attributes available for mass-assignment for all models
    # in your app. As such, your models will need to explicitly whitelist or blacklist accessible
    # parameters by using an attr_accessible or attr_protected declaration.
    config.active_record.whitelist_attributes = true

    # Enable the asset pipeline
    config.assets.enabled = true
		
    # Version of your assets, change this if you want to expire all your assets
    config.assets.version = '1.0'

    ## configure logging
    if Rails.env == "production" then
    	config.log_level = :warn
    else
    	config.log_level = :debug
		end

		## force SSL
		if Rails.env == "production" then
			config.force_ssl = true
		end

		## Setup SSH tunnels
		load File.join(config.root, 'config','tunnels',"tunnel.rb")

		## make the log files host specific
		config.paths['log'] = File.join(config.root, "log", "#{Rails.env}-#{Socket.gethostname}.log")

  end
end
